# Generated by Django 4.1.2 on 2022-10-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_economiccalender_forecast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='session',
            new_name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('news', 'news'), ('article', 'article'), ('education', 'education')], max_length=10),
        ),
    ]
